version: '3.8'
services:
  backend:
    container_name: mr-backend
    image: mr-backend:latest
    build:
      context: ./meme-reviewer-backend
    ports:
      - "2000:5000"
  frontend:
    container_name: mr-frontend
    image: mr-frontend:slim
    build:
      context: ./meme-reviewer-frontend
      args:
        REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "30:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000